# Generated by Django 2.1 on 2018-09-09 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('rua', models.CharField(max_length=40, verbose_name='Rua')),
                ('numero', models.CharField(max_length=40, verbose_name='Número')),
                ('bairro', models.CharField(max_length=40, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=40, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=40, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=44, unique=True, verbose_name='Chave de Acesso')),
                ('numero', models.CharField(max_length=9, verbose_name='Número da NF-e')),
                ('data', models.DateField(verbose_name='Data de Emissão')),
                ('xml', models.BinaryField(blank=True, verbose_name='XML NF-e')),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Nota')),
            ],
        ),
    ]
